nodes:
- input.visual:
    source: 0
- model.yolo:
    detect_ids: ["person",
                 "cat",
                 "bottle",
                 "wine glass",
                 "cup",
                 "fork",
                 "knife",
                 "spoon",
                 "bowl",
                 "banana",
                 "apple",
                 "sandwich",
                 "orange",
                 "broccoli",
                 "carrot",
                 "hot dog",
                 "pizza",
                 "donut",
                 "cake",
                 "chair",
                 "couch",
                 "potted plant",
                 "bed",
                 "laptop",
                 "keyboard",
                 "mouse",
                 "dining table",
                 "toilet",
                 "tv",
                 "laptop",
                 "mouse",
                 "remote",
                 "keyboard",
                 "cell phone",
                 "microwave",
                 "oven",
                 "toaster",
                 "sink",
                 "refrigerator",
                 "book",
                 "clock",
                 "vase",
                 "scissors",
                 "teddy bear",
                 "hair drier",
                 "toothbrush"]
- draw.bbox:
    show_labels: True
- output.screen
