# Mandatory configs
# Receive bounding boxes and their respective labels as input. Replace with
# other data types as required. List of built-in data types for PeekingDuck can
# be found at https://peekingduck.readthedocs.io/en/stable/glossary.html.
input: ["img"]
output: ["bboxes", "bbox_labels"]

weights_parent_dir: model/best.pt
class_label_map: {
    0: "Aluminium Foil",
    1: "Bottle",
    2: "Bottle Cap",
    3: "Can",
    4: "Carton",
    5: "Cup",
    6: "Food Waste",
    7: "Other Plastic",
    8: "Paper Trash",
    9: "Plastic Trash",
    10: "Unlabeled Litter",
    11: "Cigarette"
}